# Generated by Django 4.1.7 on 2023-03-17 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habit_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='observers',
            field=models.ManyToManyField(blank=True, related_name='habits_i_am_observing', to=settings.AUTH_USER_MODEL),
        ),
    ]
